### ISSUE TITLE
Pointer Cursor

### ISSUE THREAD

**Issue by stdavis** [agrc/kitchen-sink#301]
Should the button component use a pointer cursor rather than leaving it unchanged? I think that the pointer cursor gives an additional cue that the button is clickable.

Same question for log out menu item:
<img width="249" alt="image" src="https://github.com/user-attachments/assets/13d59954-764c-41e1-a5ab-f890e0eaec6f">

**Comment by steveoh** [comment]
I'm following https://github.com/adobe/react-spectrum/wiki/Frequently-Asked-Questions-%28FAQs%29#why-dont-buttons-use-a-pointer-cursor

> which specify that most clickable elements (with the exception of links), should use an arrow cursor for all states, including hover and down.
>
> The intent is to better match native browser <button> behavior, the [CSS spec](https://www.w3.org/TR/CSS2/ui.html), [Microsoft interface guidelines](https://docs.microsoft.com/en-us/windows/apps/design/input/mouse-interactions#cursors) and [Apple interface guidelines](https://developer.apple.com/design/human-interface-guidelines/inputs/pointing-devices/).

**Comment by stdavis** [comment]
Interesting. I couldn't find any sites with buttons that use the arrow cursor including microsoft.com and apple.com. Maybe I'm looking in the wrong places. I looked for buttons that were not links like add to cart stuff.

Either way, do you want the "Sign out" menu item set to something other than text?

**Comment by steveoh** [comment]
It's possible that I interpreted that incorrectly since I also don't see the treatment I would expect after looking at all of those websites including adobes. I've reached out for clarification. 

I did have the same question and used that as an answer since the utah design system doesn't provide guidance. I thought it would be nice to follow a cited pattern but if it's not being followed in practice then it's not that nice. Whatever we do it needs to be consistent. 

I don't follow this...

> Either way, do you want the "Sign out" menu item set to something other than text?

Right now it's a [MenuItem](https://react-spectrum.adobe.com/react-aria/Menu.html) component which ultimately is a button. The menu styling needs to be updated and I have a task to do that but haven't made time yet.

**Comment by steveoh** [comment]
Adobe is sticking to their guns. 

> Yeah, I'm not sure every team/product follows these guidelines perfectly, but we wanted to as a component library.

**Comment by stdavis** [comment]
> I don't follow this...

When I hover over the "Sign out" menu item in the Avatar menu, the cursor turns to the ["text" type](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor#:~:text=in%20a%20bitmap.-,text,-The%20text%20can). It doesn't show up on a screenshot.

**Comment by steveoh** [comment]
This should be fixed with #304. I'm going to close this and we can continue this discussion internally.
